### ISSUE TITLE
When trying to start using localhost as db

### ISSUE THREAD

**Issue by jaydestro** [cefjoeii/mern-crud#1]
```
bash-3.2$ node server.js
/Users/jaygordon/mern-crud/server.js:15
let db = mongoose.connection;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
bash-3.2$
```

**Comment by jaydestro** [comment]
```
// Set the connection string based from the config vars of the production server
// To run locally use 'mongodb://localhost/mern-crud' instead of process.env.DB

module.exports = {
  db: 'mongodb://localhost/mern-crud'
};
```

**Comment by cefjoeii** [comment]
Thanks for letting us know about this. It could be that an old version of node is running on your machine. Kindly try and see if an updated one will work. I used v6.11.0.

**Comment by jaydestro** [comment]
it was def the version - upgrading to this corrected it.
